# Site settings
title_head: PPN  UNP-Kediri
title: ppn.unpkediri.ac.id
email: ppn@unpkediri.ac.id
description: > # this means to ignore newlines until "baseurl:"
  UKM Penalaran dan Penelitian adalah UKM yang merupakan kelengkapan 
  non Struktural di Universitas Nusantara PGRI Kediri dan Melaksanakan 
  tugas penelitian yang berada dibawah koordinasi Lembaga Penelitian.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ppn.unpkediri.ac.id" # the base hostname & protocol for your site
twitter_username: saifulindo
github_username:  ukmppn-unp

# Build settings
markdown: kramdown
highlighter: rouge